version: "3.8"

services:
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: on-failure
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_NAME: ${USER_DB_NAME}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      #      - JAEGER_SERVICE_NAME=${JAEGER_SERVICE_NAME}
      #      - JAEGER_AGENT_HOST=tracing
      #      - JAEGER_AGENT_PORT=6831
      #      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      #      - JAEGER_SAMPLER_TYPE=const
      #      - JAEGER_SAMPLER_PARAM=1
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      REGISTER_USER_COMMAND_SUBJECT: ${REGISTER_USER_COMMAND_SUBJECT}
      REGISTER_USER_REPLY_SUBJECT: ${REGISTER_USER_REPLY_SUBJECT}
      PATCH_USER_COMMAND_SUBJECT: ${PATCH_USER_COMMAND_SUBJECT}
      PATCH_USER_REPLY_SUBJECT: ${PATCH_USER_REPLY_SUBJECT}
      UPDATE_USER_COMMAND_SUBJECT: ${UPDATE_USER_COMMAND_SUBJECT}
      UPDATE_USER_REPLY_SUBJECT: ${UPDATE_USER_REPLY_SUBJECT}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    depends_on:
      - user_db
    #      - tracing
    networks:
      - network
    ports:
      - "8081:8000"

  post_service:
    image: post_service
    container_name: post_service
    build:
      context: .
      dockerfile: ./post_service/Dockerfile
    restart: on-failure
    environment:
      POST_DB_HOST: ${POST_DB_HOST}
      POST_DB_PORT: ${POST_DB_PORT}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      REGISTER_USER_COMMAND_SUBJECT: ${REGISTER_USER_COMMAND_SUBJECT}
      REGISTER_USER_REPLY_SUBJECT: ${REGISTER_USER_REPLY_SUBJECT}
      UPDATE_USER_COMMAND_SUBJECT: ${UPDATE_USER_COMMAND_SUBJECT}
      UPDATE_USER_REPLY_SUBJECT: ${UPDATE_USER_REPLY_SUBJECT}
    depends_on:
      - post_db
    networks:
      - network
    ports:
      - "8082:8000"

  additional_user_service:
    image: additional_user_service
    container_name: additional_user_service
    build:
      context: .
      dockerfile: ./additional_user_service/Dockerfile
    restart: on-failure
    environment:
      ADDITIONAL_USER_DB_HOST: ${ADDITIONAL_USER_DB_HOST}
      ADDITIONAL_USER_DB_PORT: ${ADDITIONAL_USER_DB_PORT}
      ADDITIONAL_USER_SERVICE_PORT: ${ADDITIONAL_USER_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      REGISTER_USER_COMMAND_SUBJECT: ${REGISTER_USER_COMMAND_SUBJECT}
      REGISTER_USER_REPLY_SUBJECT: ${REGISTER_USER_REPLY_SUBJECT}
    depends_on:
      - additional_user_db
    networks:
      - network
    ports:
      - "8083:8000"

  connection_service:
    image: connection_service
    container_name: connection_service
    build:
      context: .
      dockerfile: ./connection_service/Dockerfile
    restart: on-failure
    environment:
      - CONNECTION_DB_HOST=${CONNECTION_DB_HOST}
      - CONNECTION_DB_PORT=${CONNECTION_DB_PORT}
      - CONNECTION_SERVICE_PORT=${CONNECTION_SERVICE_PORT}
      - CONNECTION_DB_USER=${CONNECTION_DB_USER}
      - CONNECTION_DB_PASS=${CONNECTION_DB_PASS}
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
      - NATS_USER=${NATS_USER}
      - NATS_PASS=${NATS_PASS}
      - REGISTER_USER_COMMAND_SUBJECT=${REGISTER_USER_COMMAND_SUBJECT}
      - REGISTER_USER_REPLY_SUBJECT=${REGISTER_USER_REPLY_SUBJECT}
      - PATCH_USER_COMMAND_SUBJECT=${PATCH_USER_COMMAND_SUBJECT}
      - PATCH_USER_REPLY_SUBJECT=${PATCH_USER_REPLY_SUBJECT}
    depends_on:
      - neo4j
    networks:
      - network
    ports:
      - "8084:8000"

  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: on-failure
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASS: ${AUTH_DB_PASS}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      REGISTER_USER_COMMAND_SUBJECT: ${REGISTER_USER_COMMAND_SUBJECT}
      REGISTER_USER_REPLY_SUBJECT: ${REGISTER_USER_REPLY_SUBJECT}
      UPDATE_USER_COMMAND_SUBJECT: ${UPDATE_USER_COMMAND_SUBJECT}
      UPDATE_USER_REPLY_SUBJECT: ${UPDATE_USER_REPLY_SUBJECT}
    depends_on:
      - auth_db
    networks:
      - network
    ports:
      - "8085:8000"

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      ADDITIONAL_USER_SERVICE_HOST: ${ADDITIONAL_USER_SERVICE_HOST}
      ADDITIONAL_USER_SERVICE_PORT: ${ADDITIONAL_USER_SERVICE_PORT}
      CONNECTION_SERVICE_HOST: ${CONNECTION_SERVICE_HOST}
      CONNECTION_SERVICE_PORT: ${CONNECTION_SERVICE_PORT}
    networks:
      - network
  #      - jaeger-demo
  #    depends_on:
  #      - tracing

  user_db:
    image: postgres
    container_name: user_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASS}
      POSTGRES_DB: ${USER_DB_NAME}
    networks:
      - network

  auth_db:
    image: postgres
    container_name: auth_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
    networks:
      - network

  post_db:
    image: mongo
    container_name: post_db
    restart: on-failure
    networks:
      - network

  neo4j:
    image: neo4j:4.3.3-community #4.3.3-community  latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - network
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=512M

  additional_user_db:
    image: mongo
    container_name: additional_user_db
    restart: on-failure
    networks:
      - network

  #  tracing:
  #    image: jaegertracing/all-in-one
  #    container_name: jaeger
  #    ports:
  #      - "6831:6831/udp"
  #      - "6832:6832/udp"
  #      - "16686:16686"
  #      - "14268:14268"
  #      - "14250:14250"
  #    networks:
  #      - jaeger-demo

  nats:
    image: nats
    container_name: nats
    restart: on-failure
    networks:
      - network
    ports:
      - 8222:8222
      - 4222:4222
      - 6222:6222

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - network

  grafana:
    image: grafana/grafana:8.0.4
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3031:3000
    networks:
      - network

#  postman:
#    image: postman/newman_ubuntu1404:4.5.5
#    build:
#      context: .
#      dockerfile: initCalls/Dockerfile
#    entrypoint: [ "" ]
#    volumes:
#      - /initCalls:/etc/newman
#    command: >
#      newman run /initCalls/src/INSERT_DATA.postman_collection.json
#      -r cli
#      --delay-request 7000
#      --timeout-request 20000
#    depends_on:
#      - additional_user_service
#      - connection_service
#      - auth_service
#      - post_service
#      - api_gateway
#      - user_service
#    networks:
#      - network

volumes:
  prometheus-data:
  grafana-data:

networks:
  network:
    driver: bridge

#  jaeger-demo:
